packages:
	yum:
		libcurl-devel: []
		libcurl4-openssl-dev: []
		libssl-dev: []
		python-pycurl: []
commands:
    01_pycurl_install:
        command: sudo /opt/python/run/venv/bin/pip3 install pycurl --global-option="--with-openssl"
