packages:
	yum:
		gcc: []
		libcurl-devel: []
		libcurl4-openssl-dev: []
		libssl-dev: []
		python3-pycurl: []
		openssl-static.x86_64: []
commands:
    01_pycurl_install:
        command: sudo /opt/python/run/venv/bin/pip3 install pycurl --global-option="--with-openssl"
