CREATE TABLE IF NOT EXISTS Atributos_Falabella(
    id int NOT NULL AUTO_INCREMENT,
    Label varchar(256) NOT NULL,
    Category VARCHAR(256) NOT NULL,
    GroupName varchar(256) NULL,
    isMandatory BOOL NOT NULL,
    isGlobalAttribute BOOL NOT NULL,
    Description MEDIUMTEXT NULL,
    ProductType VARCHAR(64) NULL,
    AttributeType VARCHAR(12) NOT NULL,
    Options TEXT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_MercadoLibre(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(120) NOT NULL,
    Category VARCHAR(60) NOT NULL,
    Tags VARCHAR(120) NOT NULL,
    Hierarchy VARCHAR(20) NOT NULL,
    AttributeType VARCHAR(15) NOT NULL,
    GroupName VARCHAR(64) NOT NULL,
    Options TEXT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_Paris(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(64) NOT NULL,
    Category VARCHAR(40) NOT NULL,
    Family VARCHAR(20) NOT NULL,
    AttributeType VARCHAR(16) NOT NULL,
    GroupName VARCHAR(20) NULL,
    isMandatory BOOL NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_Ripley(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(64) NOT NULL,
    Category VARCHAR(80) NOT NULL,
    RequirementLevel CHAR(8) NOT NULL,
    AttributeType VARCHAR(10) NOT NULL,
    Options VARCHAR(120) NULL,
    Variant BOOL NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Falabella(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(45) NOT NULL,
    Atributo VARCHAR(36) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_MercadoLibre(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(70) NOT NULL,
    Atributo VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Paris(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(50) NOT NULL,
    Atributo VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Ripley(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(45) NOT NULL,
    Atributo VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Categorias(
    id INT NOT NULL AUTO_INCREMENT,
    Multivende VARCHAR(150) NOT NULL,
    MercadoLibre VARCHAR(150) NOT NULL,
    Falabella VARCHAR(220) NOT NULL,
    Ripley VARCHAR(200) NOT NULL,
    Paris VARCHAR(120) NOT NULL,
    Paris_Familia VARCHAR(30) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Productos_standard(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    Season varchar(64) NULL,
    model varchar(160) NULL,
    description MEDIUMTEXT NULL,
    htmlDescription MEDIUMTEXT NULL,
    shortDescription MEDIUMTEXT NULL,
    htmlShortDescription MEDIUMTEXT NULL,
    Warranty VARCHAR(16) NULL,
    Brand VARCHAR(20) NULL,
    name VARCHAR(128) NOT NULL,
    ProductCategory VARCHAR(136) NULL,
    sku_name VARCHAR(16) NULL,
    color VARCHAR(16) NULL,
    size VARCHAR(16) NULL,
    sku VARCHAR(16) NULL,
    internalSku VARCHAR(16) NULL,
    width FLOAT NULL,
    length FLOAT NULL,
    height FLOAT NULL,
    weight FLOAT NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);

CREATE TABLE IF NOT EXISTS Productos_MercadoLibre(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    `Cantidad de ventiladores-Mercado Libre Productos (HB)` INT NULL,
    `Es articulado-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Peso del paquete - PACKAGE_WEIGHT-Mercado Libre Versiones (HB)` VARCHAR(10) NULL,
    `Flujo luminoso máximo-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Es apto para barba-Mercado Libre Productos (HB)` VARCHAR(4) NULL,
    `Formato de venta - SALE_FORMAT-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Autonomía mínima de horas-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Con Bluetooth - WITH_BLUETOOTH-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Con pantalla LCD - WITH_LCD_SCREEN-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es plegable - IS_FOLDABLE-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Dispositivos compatibles-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Profundidad - DEPTH-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Flexible - FLEXIBLE-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Capacidad-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tipo de colador - COLANDER_TYPE-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Embalaje del envío-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Peso de Producto-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Es una pistola masajeadora-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Velocidad máxima - MAX_SPEED-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Es antibacteriana-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Apertura - APERTURE-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Con wi-fi-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Resistencia - RESISTANCE-Mercado Libre Versiones (HB)` VARCHAR(32) NULL,
    `Control de temperatura-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Incluye cepillo-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Con ruedas - WITH_WHEELS-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Capacidad de platos-Mercado Libre Productos (HB)` INT NULL,
    `Voltaje - VOLTAGE-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Material del trípode-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Es inclinable-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye batería recargable-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es antiácaros-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Autonomía máxima de horas-Mercado Libre Productos (HB)` INT NULL,
    `Zona de Aplicación-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Es inalámbrico - IS_WIRELESS-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Tipo de telescopio - TELESCOPE_TYPE-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Temperatura máxima del cepillo-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Cantidad de niveles - TIERS_NUMBER-Mercado Libre Productos (HB)` INT NULL,
    `Tipo de telescopio-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Tipo de plancha-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Diseño óptico-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Tipo-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Incluye molde para tortas-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye cabezal - INCLUDES_HEAD-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Material - MATERIAL-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tipo de uso-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Distancia focal-Mercado Libre Productos (HB)` VARCHAR(7) NULL,
    `Forma de almohada - PILLOW_SHAPE-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Incluye estuche - INCLUDES_CASE-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Diámetro del objetivo-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Alto de producto-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Cantidad de faros-Mercado Libre Productos (HB)` INT NULL,
    `Con mango ergonómico-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es fijo-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Materiales del relleno-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Apertura-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Es gamer-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Largo de Producto-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Largo del paquete - PACKAGE_LENGTH-Mercado Libre Versiones (HB)` VARCHAR(8) NULL,
    `Presión máxima - MAX_PRESSURE-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Código universal de producto - GTIN-Mercado Libre Versiones (HB)` BIGINT  NULL,
    `Uso de la plancha-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Unidades por pack - UNITS_PER_PACK-Mercado Libre Productos (HB)` INT NULL,
    `Tipo - JUMP_ROPE_TYPE-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tiempo de carga de la batería-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tamaño máximo de la notebook-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Incluye balizas reflactarias-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Línea - LINE-Mercado Libre Productos (HB)` VARCHAR(20) NULL,
    `Largo de la espada-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Caudal de aire - AIRFLOW-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Potencia - POWER-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Incluye manguera-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye tabla - INCLUDES_BOARD-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Con aromaterapia-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Con lubricación automática-Mercado Libre Productos (HB` CHAR(2) NULL,
    `Altura máxima - MAXIMUM_HEIGHT-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Espesor - THICKNESS-Mercado Libre Productos (HB)` VARCHAR(7) NULL,
    `Tipo de consola-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Conectividad de red móvil-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tipo de revestimiento exterior-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Accesorios incluidos-Mercado Libre Productos (HB)` TEXT NULL,
    `Potencia máxima-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Cantidad de puertos USB-Mercado Libre Productos (HB)` INT NULL,
    `Incluye matafuego-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Montura-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Es portátil - IS_PORTABLE-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Diseño óptico - OPTICAL_DESIGN-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Material de la olla - POT_MATERIAL-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Peso del compresor de aire-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Es antihongos-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Altura del paquete - PACKAGE_HEIGHT-Mercado Libre Versiones (HB)` VARCHAR(8) NULL,
    `Año de lanzamiento-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Flujo luminoso mínimo-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Diámetro de Producto-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Edad mínima recomendada-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Tipo de revestimiento interior-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Tipos de cocinas compatibles-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Diámetro - DIAMETER-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Estándares VESA-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Unidades por envase-Mercado Libre Productos (HB)` INT NULL,
    `Tamaño mínimo de la pantalla-Mercado Libre Productos (HB)` VARCHAR(4) NULL,
    `Tipo de fondo-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Con regulador de velocidad-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Tipo de luz-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Lugar de montaje-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Distancia máxima del foco-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Nivel de presión sonora-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Es inteligente - IS_INTELLIGENT-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Velocidad de rotación-Mercado Libre Productos (HB)` VARCHAR(10) NULL,
    `Tipo de cinta adhesiva-Mercado Libre Productos (HB)` VARCHAR(12) NULL,
    `Con arranque fácil-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es vaporizador-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Potencia del motor - MOTOR_POWER-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Tipos de pantallas soportadas-Mercado Libre Productos (HB)` VARCHAR(36) NULL,
    `Es giratorio-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Capacidad en volumen-Mercado Libre Productos (HB)` VARCHAR(9) NULL,
    `Incluye molde para muffins-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `RESISTANCE_BAND_WITH_HANDLES-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye cuchillo - INCLUDES_KNIFE-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Edición-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Color - COLOR-Mercado Libre Versiones (HB)` VARCHAR(16) NULL,
    `Características del producto-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Con revestimiento antiadherente-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye pedales - INCLUDES_PEDALS-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es mini - IS_MINI-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Con visión nocturna-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Submodelo-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Cantidad de luces LED-Mercado Libre Productos (HB)` INT NULL,
    `Con función de planchado vertical-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Ancho del paquete - PACKAGE_WIDTH-Mercado Libre Versiones (HB)` VARCHAR(8) NULL,
    `Material Producto-Mercado Libre Productos (HB)` VARCHAR(20) NULL,
    `Altura mínima - MINIMUM_HEIGHT-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Ancho de producto-Mercado Libre Productos (HB)` VARCHAR(8) NULL,
    `Tipo de alimentación-Mercado Libre Productos (HB)` VARCHAR(24) NULL,
    `Incluye manual de rutinas-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Tipo de olla - POT_TYPE-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Cantidad de sistemas de seguridad-Mercado Libre Productos (HB)` INT NULL,
    `Con sistema de cierre automático-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Material del escurridor de vajilla-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Cantidad de piezas - PIECES_NUMBER-Mercado Libre Productos (HB)` INT NULL,
    `Es hipoalergénica-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Lugar de colocación-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Aumento - MAGNIFICATION-Mercado Libre Productos (HB)` VARCHAR(10) NULL,
    `Superficies recomendadas-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    `Montura - MOUNT-Mercado Libre Productos (HB)` VARCHAR(16) NULL,
    `Peso máximo de usuario-Mercado Libre Productos (HB)` VARCHAR(6) NULL,
    `Tamaño máximo de la pantalla-Mercado Libre Productos (HB)` VARCHAR(4) NULL,
    `Tamaño Pantalla-Mercado Libre Productos (HB)` VARCHAR(4) NULL,
    `Incluye picos pasteleros-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es estación de planchado-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Es a prueba de agua-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Incluye tapa - INCLUDES_LID-Mercado Libre Productos (HB)` CHAR(2) NULL,
    `Zonas de aplicación-Mercado Libre Productos (HB)` VARCHAR(32) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);

CREATE TABLE IF NOT EXISTS Productos_Falabella(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    `Incluye-Falabella Productos` TEXT NULL,
    `Tipo de mascota-Falabella Productos` VARCHAR(16) NULL,
    `Consumo energético-Falabella Productos` VARCHAR(16) NULL,
    `Tipo de soporte-Falabella Productos` VARCHAR(16) NULL,
    `Material-Falabella Productos` VARCHAR(62) NULL,
    `Unidad de medida-Falabella Productos` VARCHAR(5) NULL,
    `Resolución de pantalla-Falabella Productos` VARCHAR(18) NULL,
    `Voltaje-Falabella Productos` VARCHAR(9) NULL,
    `Variante-Falabella Productos` VARCHAR(36) NULL,
    `Conectividad/conexión-Falabella Productos` VARCHAR(16) NULL,
    `Color-Falabella Productos` VARCHAR(16) NULL,
    `Recomendaciones-Falabella Productos` TEXT NULL,
    `Condición del producto-Falabella Productos` VARCHAR(32) NULL,
    `Tipo de Olla-Falabella Productos` VARCHAR(16) NULL,
    `Niveles de potencia-Falabella Productos` VARCHAR(5) NULL,
    `Tipo automotriz-Falabella Productos` VARCHAR(32) NULL,
    `Zoom óptico-Falabella Productos` VARCHAR(12) NULL,
    `Nombre-Falabella Productos` VARCHAR(255) NULL,
    `Tipo Freidora-Falabella Productos` VARCHAR(32) NULL,
    `Posición de descanso-Falabella Productos` VARCHAR(16) NULL,
    `Niveles de temperatura-Falabella Productos` VARCHAR(25) NULL,
    `Largo de la manguera-Falabella Productos` VARCHAR(6) NULL,
    `Incluye trípode-Falabella Productos` CHAR(2) NULL,
    `Descripción Inpage HTML Falabella-Falabella Productos` TEXT NULL,
    `Tipo de mueble-Falabella Productos` VARCHAR(32) NULL,
    `Tipo de cerradura-Falabella Productos` VARCHAR(18) NULL,
    `Tipo de ensamblado-Falabella Productos` VARCHAR(32) NULL,
    `Tipo de tablet-Falabella Productos` VARCHAR(16) NULL,
    `Tipo de accesorio para tablets-Falabella Productos` VARCHAR(32) NULL,
    `Diámetro del lente-Falabella Productos` VARCHAR(9) NULL,
    `Flujo luminoso-Falabella Productos` VARCHAR(12) NULL,
    `Potencia-Falabella Productos` VARCHAR(6) NULL,
    `Detalle de la condición-Falabella Productos` VARCHAR(16) NULL,
    `Resolución ISP-Falabella Productos` VARCHAR(16) NULL,
    `Garantía del vendedor-Falabella Productos` VARCHAR(32) NULL,
    `Modelo del auto-Falabella Productos` VARCHAR(16) NULL,
    `Tipo de luz-Falabella Productos` VARCHAR(12) NULL,
    `Tipo de balanza-Falabella Productos` VARCHAR(32) NULL,
    `Características belleza-Falabella Productos` VARCHAR(32) NULL,
    `Código de barras-Falabella Versiones` VARCHAR(16) NULL,
    `Forma farmacéutica-Falabella Productos` VARCHAR(32) NULL,
    `Uso de la herramienta-Falabella Productos` VARCHAR(32) NULL,
    `Color básico-Falabella Productos` VARCHAR(16) NULL,
    `Ancho Falabella-Falabella Productos` VARCHAR(8) NULL,
    `Autonomía-Falabella Productos` VARCHAR(16) NULL,
    `Presión máxima-Falabella Productos` VARCHAR(8) NULL,
    `Tipo de bolsa-Falabella Productos` VARCHAR(12) NULL,
    `Tipo de utensilio de cocina-Falabella Productos` VARCHAR(16) NULL,
    `Tipo de velocidad-Falabella Productos` VARCHAR(16) NULL,
    `Superficie de aplicación-Falabella Productos` VARCHAR(32) NULL,
    `Firmeza de la almohada-Falabella Productos` VARCHAR(16) NULL,
    `Material de electrodomésticos-Falabella Productos` VARCHAR(32) NULL,
    `Peso del producto-Falabella Productos` VARCHAR(8) NULL,
    `Tipo de accesorio de ferretería-Falabella Productos` VARCHAR(32) NULL,
    `Temperatura máxima-Falabella Productos` VARCHAR(5) NULL,
    `Velocidad-Falabella Productos` VARCHAR(10) NULL,
    `Tipo de masajeador-Falabella Productos` VARCHAR(16) NULL,
    `Peso máximo soportado-Falabella Productos` VARCHAR(9) NULL,
    `Alimentación-Falabella Productos` VARCHAR(24) NULL,
    `Número de dientes-Falabella Productos` INT NULL,
    `Sistema de recolección-Falabella Productos` VARCHAR(16) NULL,
    `Garantía del producto-Falabella Productos` VARCHAR(8) NULL,
    `Descripción-Falabella Productos` TEXT NULL,
    `Dimensiones-Falabella Productos` VARCHAR(48) NULL,
    `Cámara posterior-Falabella Productos` VARCHAR(7) NULL,
    `Número de piezas-Falabella Productos` VARCHAR(10) NULL,
    `Con HDMI-Falabella Productos` CHAR(2) NULL,
    `Cable retráctil-Falabella Productos` CHAR(2) NULL,
    `Requiere Serial Number-Falabella Productos` CHAR(2) NULL,
    `Largo del cable-Falabella Productos` VARCHAR(9) NULL,
    `Uso-Falabella Productos` VARCHAR(32) NULL,
    `Diámetro del disco-Falabella Productos` VARCHAR(8) NULL,
    `Largo Falabella-Falabella Productos` VARCHAR(8) NULL,
    `Medida/volumen-Falabella Productos` VARCHAR(9) NULL,
    `Capacidad-Falabella Productos` VARCHAR(14) NULL,
    `Aplicación-Falabella Productos` VARCHAR(16) NULL,
    `Alcance-Falabella Productos` VARCHAR(16) NULL,
    `Compatible con-Falabella Productos` VARCHAR(32) NULL,
    `Alto Falabella-Falabella Productos` VARCHAR(8) NULL,
    `Cantidad contenida en el empaque-Falabella Productos` VARCHAR(160) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);
    
CREATE TABLE IF NOT EXISTS Productos_Ripley(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    `Lector De Tarjetas-Ripley Productos` CHAR(2) NULL,
    `Conectividad-Ripley Productos` VARCHAR(16) NULL,
    `Modelo del auto-Ripley Productos` VARCHAR(16) NULL,
    `Cortacorriente integrado-Ripley Productos` CHAR(2) NULL,
    `Diametro Máximo (Mm)-Ripley Productos` VARCHAR(8) NULL,
    `Diseño TV - disenoTv-Ripley Productos` VARCHAR(16) NULL,
    `Potencia (W)-Ripley Productos` VARCHAR(18) NULL,
    `Entrada para micrófono-Ripley Productos` CHAR(2) NULL,
    `Peso (kg)-Ripley Productos` VARCHAR(6) NULL,
    `Combustible-Ripley Productos` VARCHAR(16) NULL,
    `Marca del Auto-Ripley Productos` VARCHAR(16) NULL,
    `Diseño Todas las Categorias-Ripley Productos` VARCHAR(32) NULL,
    `Descripción Inpage HTML Ripley-Ripley Productos` TEXT NULL,
    `Profundidad-Ripley Productos` VARCHAR(6) NULL,
    `Distancia Focal-Ripley Productos` VARCHAR(10) NULL,
    `Memoria Interna-Ripley Productos` VARCHAR(16) NULL,
    `Calidad-Ripley Productos` VARCHAR(16) NULL, 
    `Tipo Procesador-Ripley Productos` VARCHAR(12) NULL,
    `Diseño TV-Ripley Productos` VARCHAR(8) NULL,
    `Modelo-Ripley Productos` VARCHAR(160) NULL,
    `Tipo Deporte-Ripley Productos` VARCHAR(32) NULL,
    `Bluetooth-Ripley Productos` CHAR(2) NULL,
    `Control De Temperatura-Ripley Productos` VARCHAR(12) NULL,
    `Duración Batería (Hr)-Ripley Productos` VARCHAR(6) NULL,
    `Material de la estructura-Ripley Productos` VARCHAR(22) NULL,
    `Tipo De Montura-Ripley Productos` VARCHAR(12) NULL,
    `Visión Nocturna-Ripley Productos` CHAR(2) NULL,
    `Tamaño Pantalla-Ripley Productos` VARCHAR(4) NULL,
    `Memoria Ram-Ripley Productos` VARCHAR(10) NULL,
    `Niveles de potencia-Ripley Productos` VARCHAR(16) NULL,
    `Color Ripley-Ripley Productos` VARCHAR(16) NULL,
    `Funciones-Ripley Productos` VARCHAR(32) NULL,
    `Eficiencia Energética-Ripley Productos` VARCHAR(36) NULL,
    `Sintonizador Digital-Ripley Productos` CHAR(2) NULL,
    `Tipo de Instrumento-Ripley Productos` VARCHAR(16) NULL,
    `Rociador-Ripley Productos` VARCHAR(16) NULL,
    `País De Fabricación-Ripley Productos` VARCHAR(16) NULL,
    `Número de teclas-Ripley Productos` VARCHAR(5) NULL,
    `Capacidad-Ripley Productos` VARCHAR(16) NULL,
    `Alimentación-Ripley Productos` VARCHAR(26) NULL,
    `panel digital-Ripley Productos` CHAR(2) NULL,
    `Tipo de Prenda-Ripley Productos` VARCHAR(16) NULL,
    `Conexión VGA-Ripley Productos` CHAR(2) NULL,
    `Material Cuerpo-Ripley Productos` VARCHAR(20) NULL,
    `URL 3D-Ripley Productos` VARCHAR(32) NULL,
    `Keywords-Ripley Productos` VARCHAR(32) NULL,
    `Resolución Salida Video-Ripley Productos` VARCHAR(16) NULL,
    `Rueda De Enfoque-Ripley Productos` CHAR(2) NULL,
    `Tiempo de Carga-Ripley Productos` VARCHAR(12) NULL,
    `Tipo Mascota-Ripley Productos` VARCHAR(16) NULL,
    `Número de Quemadores-Ripley Productos` VARCHAR(14) NULL,
    `Velocidad Procesador-Ripley Productos` VARCHAR(16) NULL,
    `Tipo de Pantalla-Ripley Productos` VARCHAR(12) NULL,
    `Sección-Ripley Productos` VARCHAR(32) NULL,
    `Autonomía-Ripley Productos` VARCHAR(10) NULL,
    `Ángulo de Visión-Ripley Productos` VARCHAR(5) NULL,
    `Tipo De Cierre-Ripley Productos` VARCHAR(16) NULL,
    `Consumo-Ripley Productos` VARCHAR(12) NULL,
    `Cabezales Intercambiables-Ripley Productos` CHAR(2) NULL,
    `Motor (HP)-Ripley Productos` VARCHAR(5) NULL,
    `Alimentación del vehículo (V)-Ripley Productos` VARCHAR(12) NULL,
    `HDMI-Ripley Productos` VARCHAR(8) NULL,
    `Tamaño Rueda-Ripley Productos` VARCHAR(6) NULL,
    `Apagado Automático-Ripley Productos` CHAR(2) NULL,
    `Presentación-Ripley Productos` VARCHAR(16) NULL,
    `Estado de la oferta-Ripley Productos` VARCHAR(16) NULL,
    `Material-Ripley Productos` VARCHAR(64) NULL,
    `Material De La Base-Ripley Productos` VARCHAR(18) NULL,
    `Número De Focos-Ripley Productos` INT NULL, 
    `Duración Batería-Ripley Productos` VARCHAR(6) NULL,
    `Motor-Ripley Productos` VARCHAR(12) NULL,
    `Cantidad puertos USB-Ripley Productos` INT NULL,
    `Aspira líquidos-Ripley Productos` CHAR(2) NULL,
    `Rango de Cobertura-Ripley Productos` VARCHAR(10) NULL,
    `Compatibilidad-Ripley Productos` VARCHAR(160) NULL,
    `Tamaño Raza-Ripley Productos` VARCHAR(16) NULL,
    `Tipo de Batería-Ripley Productos` VARCHAR(32) NULL,
    `Condicion de Producto-Ripley Productos` VARCHAR(10),
    `Diseño Óptico Binoculares y Telescopios-Ripley Productos` VARCHAR(16) NULL,
    `Wi-Fi-Ripley Productos` CHAR(2) NULL,
    `Número Puertos HDMI-Ripley Productos` INT NULL,
    `Amperaje de entrada-Ripley Productos` VARCHAR(14) NULL,
    `Numero de piezas-Ripley Productos` VARCHAR(10) NULL,
    `Tipo de conector-Ripley Productos` VARCHAR(16) NULL,
    `Tipo de producto (todos)-Ripley Productos` VARCHAR(42) NULL,
    `Micrófono-Ripley Productos` VARCHAR(12) NULL,
    `Memoria Expandible-Ripley Productos` CHAR(2) NULL,
    `Talla-Ripley Versiones` VARCHAR(12) NULL,
    `Certificación SEC-Ripley Productos` VARCHAR(16) NULL,
    `Material de las cuchillas / batidoras-Ripley Productos` VARCHAR(18) NULL,
    `Compromiso R-Ripley Productos` VARCHAR(32) NULL,
    `Aumento-Ripley Productos` VARCHAR(25) NULL,
    `EAN-Ripley Productos` VARCHAR(16) NULL,
    `Tipo de freno-Ripley Productos` VARCHAR(8) NULL,
    `Cobertura (m²)-Ripley Productos` VARCHAR(9) NULL,
    `Inalámbrico-Ripley Productos` CHAR(2) NULL,
    `Regulador De Vapor-Ripley Productos` CHAR(2) NULL,
    `Antiadherente-Ripley Productos` CHAR(2) NULL,
    `Resistente Al Agua-Ripley Productos` CHAR(2) NULL,
    `Resolución video-Ripley Productos` VARCHAR(22) NULL,
    `Forma-Ripley Productos` VARCHAR(16) NULL,
    `Tipo de filtro-Ripley Productos` VARCHAR(16) NULL,
    `Talla Ripley-Ripley Productos` VARCHAR(12) NULL,
    `Alto-Ripley Productos` VARCHAR(6) NULL,
    `Sensibilidad GPS (dBm)-Ripley Productos` VARCHAR(7) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);
    
CREATE TABLE IF NOT EXISTS Productos_Paris(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    `Dimensiones-Paris Productos` VARCHAR(48) NULL,
    `Potencia (W)-Paris Productos` VARCHAR(20) NULL,
    `Sintonizador Digital - sintonizadorDigital-Paris Productos` CHAR(2) NULL,
    `Numero de velocidades-Paris Productos` VARCHAR(15) NULL,
    `Aro de bicicleta-Paris Productos` VARCHAR(9) NULL,
    `Tratamiento-Paris Productos` VARCHAR(26) NULL,
    `Memoria Ram-Paris Productos` VARCHAR(12) NULL,
    `Sistema De Seguridad Herramientas-Paris Productos` VARCHAR(150) NULL,
    `Talla-Paris Versiones` VARCHAR(12) NULL,
    `Eficiencia Energetica-Paris Productos` VARCHAR(36) NULL,
    `Conectividad (Atributo de producto)-Paris Productos` VARCHAR(28) NULL,
    `Tiempo de entrega al Courier (en días hábiles)-Paris Productos` VARCHAR(12) NULL,
    `Color-Paris Versiones` VARCHAR(12) NULL,
    `Consumo electrico-Paris Productos` VARCHAR(14) NULL,
    `Numero de piezas-Paris Productos` VARCHAR(10) NULL,
    `Talla de Bicicleta-Paris Productos` VARCHAR(10) NULL,
    `Caracteristicas-Paris Productos` TEXT NULL,
    `Material Supermercado-Paris Productos` VARCHAR(16) NULL,
    `Material-Paris Productos` VARCHAR(52) NULL,
    `Marca-Paris Productos` VARCHAR(16) NULL,
    `Tamaño Mascota-Paris Productos` VARCHAR(16) NULL,
    `Zoom Óptico - zoomOptico-Paris Productos` VARCHAR(16) NULL,
    `Plazas-Paris Productos` VARCHAR(10) NULL,
    `Genero-Paris Productos` VARCHAR(10) NULL,
    `Zoom Digital - zoomDigital-Paris Productos` VARCHAR(12) NULL,
    `Pixeles-Paris Productos` VARCHAR(16) NULL,
    `Compatibilidad-Paris Productos` VARCHAR(160) NULL,
    `Tipo de carga-Paris Productos` VARCHAR(14) NULL,
    `Condicion-Paris Productos` VARCHAR(8) NULL,
    `Certificación SEC - certificacionSec-Paris Productos` CHAR(2) NULL,
    `Tipo de memoria-Paris Productos` VARCHAR(16) NULL,
    `Descripción Inpage HTML Paris-Paris Productos` TEXT NULL,
    `Clasificacion de Edad-Paris Productos` VARCHAR(32) NULL,
    `Resistencia al Agua-Paris Productos` VARCHAR(26) NULL,
    `Tipo de encendido-Paris Productos` VARCHAR(12) NULL,
    `Contenido-Paris Productos` TEXT NULL,
    `Material del Marco-Paris Productos` VARCHAR(8) NULL,
    `Sustentable - sustentable-Paris Productos` CHAR(2) NULL,
    `Freno Trasero-Paris Productos` VARCHAR(16) NULL,
    `Producto Local-Paris Productos` CHAR(2) NULL,
    `Tamaño Pantalla TV - tamanoPantallaTv-Paris Productos` VARCHAR(16) NULL,
    `Definicion-Paris Productos` VARCHAR(16) NULL,
    `Freno Delantero-Paris Productos` VARCHAR(16) NULL,
    `Genero Mascota-Paris Productos` VARCHAR(12) NULL,
    `Quemadores-Paris Productos` VARCHAR(16) NULL,
    `Rango de Edad - rangoDeEdad-Paris Productos` VARCHAR(24) NULL,
    `Almacenamiento-Paris Productos` VARCHAR(22) NULL,
    `Batería - bateria-Paris Productos` VARCHAR(18) NULL,
    `Bandejas-Paris Productos` VARCHAR(12) NULL,
    `Mascota-Paris Productos` VARCHAR(16) NULL,
    `HDMI - hdmi-Paris Productos` VARCHAR(8) NULL,
    `Conexiones - conexiones-Paris Productos` VARCHAR(40) NULL,
    `Tasa de Refresco-Paris Productos` VARCHAR(12) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);
    
CREATE TABLE IF NOT EXISTS Productos_Shopify(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    `URL Amigable-Shopify Productos` VARCHAR(86) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);
    
CREATE TABLE IF NOT EXISTS Renombre_categorias(
    Viejo VARCHAR(120) NOT NULL PRIMARY KEY,
    Nuevo VARCHAR(64) NOT NULL
);
    
CREATE TABLE IF NOT EXISTS `user` (
  `fs_webauthn_user_handle` varchar(64) DEFAULT NULL,
  `mf_recovery_codes` text DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `us_phone_number` varchar(128) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `us_totp_secrets` text DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `fs_uniquifier` varchar(64) NOT NULL,
  `confirmed_at` datetime DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL,
  `current_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(64) DEFAULT NULL,
  `current_login_ip` varchar(64) DEFAULT NULL,
  `login_count` int(11) DEFAULT NULL,
  `tf_primary_method` varchar(64) DEFAULT NULL,
  `tf_totp_secret` varchar(255) DEFAULT NULL,
  `tf_phone_number` varchar(128) DEFAULT NULL,
  `create_datetime` datetime NOT NULL DEFAULT current_timestamp(),
  `update_datetime` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `fs_uniquifier` (`fs_uniquifier`),
  UNIQUE KEY `fs_webauthn_user_handle` (`fs_webauthn_user_handle`),
  UNIQUE KEY `us_phone_number` (`us_phone_number`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    
CREATE TABLE IF NOT EXISTS `role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `permissions` text DEFAULT NULL,
  `update_datetime` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
    
    

CREATE TABLE IF NOT EXISTS auth(
    token TEXT NOT NULL,
    expire DATETIME NOT NULL
);