CREATE TABLE IF NOT EXISTS Atributos_Falabella(
    id int NOT NULL AUTO_INCREMENT,
    Label varchar(256) NOT NULL,
    Category VARCHAR(256) NOT NULL,
    GroupName varchar(256) NULL,
    isMandatory BOOL NOT NULL,
    isGlobalAttribute BOOL NOT NULL,
    Description MEDIUMTEXT NULL,
    ProductType VARCHAR(64) NULL,
    AttributeType VARCHAR(12) NOT NULL,
    Options TEXT(35000) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_MercadoLibre(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(120) NOT NULL,
    Category VARCHAR(60) NOT NULL,
    Tags VARCHAR(120) NOT NULL,
    Hierarchy VARCHAR(20) NOT NULL,
    AttributeType VARCHAR(15) NOT NULL,
    GroupName VARCHAR(64) NOT NULL,
    Options TEXT(35000) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_Paris(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(64) NOT NULL,
    Category VARCHAR(40) NOT NULL,
    Family VARCHAR(20) NOT NULL,
    AttributeType VARCHAR(16) NOT NULL,
    GroupName VARCHAR(20) NULL,
    isMandatory BOOL NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Atributos_Ripley(
    id INT NOT NULL AUTO_INCREMENT,
    Label VARCHAR(64) NOT NULL,
    Category VARCHAR(80) NOT NULL,
    RequirementLevel CHAR(8) NOT NULL,
    AttributeType VARCHAR(10) NOT NULL,
    Options VARCHAR(120) NULL,
    Variant BOOL NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Falabella(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(45) NOT NULL,
    Atributo VARCHAR(36) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_MercadoLibre(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(70) NOT NULL,
    Atributo VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Paris(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(50) NOT NULL,
    Atributo VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Ripley(
    id INT NOT NULL AUTO_INCREMENT,
    Mapeo VARCHAR(45) NOT NULL,
    Atributo VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Mapeo_Categorias(
    id INT NOT NULL AUTO_INCREMENT,
    Multivende VARCHAR(150) NOT NULL,
    MercadoLibre VARCHAR(150) NOT NULL,
    Falabella VARCHAR(220) NOT NULL,
    Ripley VARCHAR(200) NOT NULL,
    Paris VARCHAR(120) NOT NULL,
    Paris_Familia VARCHAR(30) NOT NULL,
    PRIMARY KEY(id)
)

CREATE TABLE Productos(
    IDENTIFICADOR_PADRE char(36) NOT NULL,
    IDENTIFICADOR_HIJO char(36) NOT NULL,
    Season varchar(64) NULL,
    model varchar(160) NULL,
    description MEDIUMTEXT NULL,
    htmlDescription MEDIUMTEXT NULL,
    shortDescription MEDIUMTEXT NULL,
    htmlShortDescription MEDIUMTEXT NULL,
    Warranty VARCHAR(16) NULL,
    Brand VARCHAR(20) NULL,
    name VARCHAR(128) NOT NULL,
    ProductCategory VARCHAR(136) NULL,
    sku_name VARCHAR(16) NULL,
    color VARCHAR(16) NULL,
    size VARCHAR(16) NULL,
    sku VARCHAR(16) NULL,
    internalSku VARCHAR(16) NULL,
    width FLOAT NULL,
    length FLOAT NULL,
    height FLOAT NULL,
    weight FLOAT NULL,
    "Cantidad de ventiladores-Mercado Libre Productos (HB)" INT NULL,
    "Es articulado-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Peso del paquete - PACKAGE_WEIGHT-Mercado Libre Versiones (HB)" VARCHAR(10) NULL,
    "Flujo luminoso máximo-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Es apto para barba - IS_SUITABLE_FOR_BEARD-Mercado Libre Productos (HB)" VARCHAR(4) NULL,
    "Formato de venta - SALE_FORMAT-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Autonomía mínima de horas-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Con Bluetooth - WITH_BLUETOOTH-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Con pantalla LCD - WITH_LCD_SCREEN-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Es plegable - IS_FOLDABLE-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Dispositivos compatibles - COMPATIBLE_DEVICES-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Profundidad - DEPTH-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Flexible - FLEXIBLE-Mercado Libre Productos (HB)" VARCHAR(8) NULL,
    "Capacidad-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tipo de colador - COLANDER_TYPE-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Embalaje del envío - SHIPMENT_PACKING-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Peso de Producto-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Es una pistola masajeadora - IS_MASSAGE_GUN-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Velocidad máxima - MAX_SPEED-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Es antibacteriana-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Apertura - APERTURE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Con wi-fi-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Resistencia - RESISTANCE-Mercado Libre Versiones (HB)" VARCHAR(32) NULL,
    "Control de temperatura - TEMPERATURE_CONTROLLER-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Incluye cepillo - INCLUDES_BARBECUE_BRUSH-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Con ruedas - WITH_WHEELS-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Capacidad de platos-Mercado Libre Productos (HB)" INT NULL,
    "Voltaje - VOLTAGE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Material del trípode-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Es inclinable-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Incluye batería recargable-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Es antiácaros-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Autonomía máxima de horas-Mercado Libre Productos (HB)" INT NULL,
    "Zona de Aplicación-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Es inalámbrico - IS_WIRELESS-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Tipo de telescopio - TELESCOPE_TYPE-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Temperatura máxima del cepillo - MAX_BRUSH_TEMPERATURE-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Cantidad de niveles - TIERS_NUMBER-Mercado Libre Productos (HB)" INT NULL,
    "Tipo de telescopio-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Tipo de plancha-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Diseño óptico-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Tipo-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Incluye molde para tortas - INCLUDES_CAKES_MOLD-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Incluye cabezal - INCLUDES_HEAD-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Material - MATERIAL-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tipo de uso - STEAM_CLEANERS_USE_TYPE-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Distancia focal-Mercado Libre Productos (HB)" VARCHAR(7) NULL,
    "Forma de almohada - PILLOW_SHAPE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Incluye estuche - INCLUDES_CASE-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Diámetro del objetivo-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Alto de producto-Mercado Libre Productos (HB)" VARCHAR(8) NULL,
    "Cantidad de faros-Mercado Libre Productos (HB)" INT NULL,
    "Con mango ergonómico - WITH_ERGONOMIC_HANDLE-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Es fijo-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Materiales del relleno-Mercado Libre Productos (HB)" VARCHAR(32) NULL,
    "Apertura-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Es gamer-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Largo de Producto-Mercado Libre Productos (HB)" VARCHAR(8) NULL,
    "Largo del paquete - PACKAGE_LENGTH-Mercado Libre Versiones (HB)" VARCHAR(8) NULL,
    "Presión máxima - MAX_PRESSURE-Mercado Libre Productos (HB)" VARCHAR(8) NULL,
    "Código universal de producto - GTIN-Mercado Libre Versiones (HB)" BIGINT  NULL,
    "Uso de la plancha-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Unidades por pack - UNITS_PER_PACK-Mercado Libre Productos (HB)" INT NULL,
    "Tipo - JUMP_ROPE_TYPE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tiempo de carga de la batería-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tamaño máximo de la notebook o netbook-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Incluye balizas reflactarias-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Línea - LINE-Mercado Libre Productos (HB)" VARCHAR(20) NULL,
    "Largo de la espada-Mercado Libre Productos (HB)" VARCHAR(9) NULL,
    "Caudal de aire - AIRFLOW-Mercado Libre Productos (HB)" VARCHAR(9) NULL,
    "Potencia - POWER-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Incluye manguera-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Incluye tabla - INCLUDES_BOARD-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Con aromaterapia-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Con lubricación automática-Mercado Libre Productos (HB" CHAR(2) NULL,
    "Altura máxima - MAXIMUM_HEIGHT-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Espesor - THICKNESS-Mercado Libre Productos (HB)" VARCHAR(7) NULL,
    "Tipo de consola-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Conectividad de red móvil-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tipo de revestimiento exterior - EXTERNAL_COATING_TYPE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Accesorios incluidos - ACCESSORIES_INCLUDED-Mercado Libre Productos (HB)" MEDIUMTEXT NULL,
    "Potencia máxima-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Cantidad de puertos USB-Mercado Libre Productos (HB)" INT NULL,
    "Incluye matafuego-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Montura-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Es portátil - IS_PORTABLE-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Diseño óptico - OPTICAL_DESIGN-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Material de la olla - POT_MATERIAL-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Peso del compresor de aire - AIR_COMPRESSOR_WEIGHT-Mercado Libre Productos (HB)" VARCHAR(6) NULL,
    "Es antihongos-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Altura del paquete - PACKAGE_HEIGHT-Mercado Libre Versiones (HB)" VARCHAR(8) NULL,
    "Año de lanzamiento-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Flujo luminoso mínimo-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Diámetro de Producto-Mercado Libre Productos (HB)" VARCHAR(9) NULL,
    "Edad mínima recomendada - MIN_RECOMMENDED_AGE-Mercado Libre Productos (HB)" VARCHAR(8) NULL,
    "Tipo de revestimiento interior - INTERNAL_COATING_TYPE-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Tipos de cocinas compatibles-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Diámetro - DIAMETER-Mercado Libre Productos (HB)" VARCHAR(9) NULL,
    "Estándares VESA-Mercado Libre Productos (HB)" VARCHAR(9) NULL,
    "Unidades por envase-Mercado Libre Productos (HB)" INT NULL,
    "Tamaño mínimo de la pantalla-Mercado Libre Productos (HB)" VARCHAR(4) NULL,
    "Tipo de fondo-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Con regulador de velocidad - WITH_SPEED_REGULATOR-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Tipo de luz-Mercado Libre Productos (HB)" VARCHAR(16) NULL,
    "Lugar de montaje-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Distancia máxima del foco - MAX_FOCUS_DISTANCE-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Nivel de presión sonora-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    "Es inteligente - IS_INTELLIGENT-Mercado Libre Productos (HB)" CHAR(2) NULL,
    "Velocidad de rotación - ROTATION_SPEED-Mercado Libre Productos (HB)" VARCHAR(10) NULL,
    "Tipo de cinta adhesiva - ADHESIVE_TAPE_TYPE-Mercado Libre Productos (HB)" VARCHAR(12) NULL,
    PRIMARY KEY(IDENTIFICADOR_PADRE, IDENTIFICADOR_HIJO)
);